// Placeholder for Astro manifest
// This will be generated by Astro build process
// For now, export an empty manifest to allow compilation

export const manifest: any = {
  adapterName: '@astrojs/node',
  routes: [],
  assets: new Set(),
  base: '/',
  assetsPrefix: undefined,
  site: 'https://lukaszpiotrluczak.me',
  componentMetadata: new Map(),
  renderers: [],
  clientDirectives: new Map(),
  entryModules: {},
};
