name: ✨ Feature request
description: Propose an improvement or new feature
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        This project is intentionally scoped.
        Please explain **why** the feature is valuable and how it aligns with the project goals.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your idea at a high level.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered other approaches?
    validations:
      required: false

  - type: checkboxes
    id: scope
    attributes:
      label: Scope impact
      options:
        - label: Frontend (Astro)
        - label: Backend (NestJS)
        - label: CI / DX
        - label: SEO / structured data
        - label: Documentation
